### ISSUE TITLE
fcitx-fbterm-helper 无法启动 dbus-launch

### ISSUE THREAD

**Issue by kamikat** [fcitx/fcitx-fbterm#3]
`dbus-launch` 属于 x11 包，在没有 X11 的条件下无法使用 dbus-launch 启动 dbus 服务

**Comment by wengxt** [comment]
早已已经不使用 dbus-launch。

**Comment by kamikat** [comment]
= = 是么……debian 6 的包看起来太早了呢…………

**Comment by wengxt** [comment]
依赖个 libX11 也不会死人的。

**Comment by kamikat** [comment]
= = 在对用着龙芯的人说么……

---

PS: Recommends 里面带个 GTK 表示就没有按 Y 的想法了……
